// ============================================
// DATA.JS - All portfolio content and data
// ============================================

const PORTFOLIO_DATA = {
  personal: {
    name: "Jothiswaran Arumugam",
    title: "AI Engineer",
    tagline: "Building production AI systems that think, act, and scale",
    email: "arumugam.jothiswaran@gmail.com",
    phone: "(850) 825-8185",
    location: "Tallahassee, FL - Open to Relocate",
    github: "https://github.com/devjothish",
    linkedin: "https://linkedin.com/in/jothiswaran",
    bio: `I've spent four years turning client problems into working AI systems - healthcare claims processing, video analysis at scale, agents that talk to databases so people don't have to write SQL. 25+ discovery and delivery engagements across healthcare, fintech, and legal, and I'm the delivery lead at an AWS Advanced Tier Partner. I'm also an AWS Golden Jacket holder, 13x AWS and 7x Google Cloud certified, because I like understanding what's running under my code.`,
    cta: `I'm looking for my next AI Engineering role. If your team is working on AI and you need someone who's shipped real systems to real users, I'd love to hear about it.`,
  },

  projects: [
    {
      id: "healthcare-mesh",
      name: "Healthcare Agentic Mesh",
      shortName: "Agentic Mesh",
      description:
        "Healthcare claims are messy - dozens of validation steps, routing rules, and edge cases. I built an agentic pipeline that runs an 8-step autonomous workflow from intake to adjudication, with tool orchestration and recovery when a step fails.",
      tech: [
        "Strands Agents SDK",
        "AWS Bedrock AgentCore",
        "Claude Sonnet",
        "ECS Fargate",
        "CDK",
        "Python",
      ],
      metrics: [
        { label: "Autonomous Steps", value: 8, suffix: "" },
        { label: "Human Handoffs", value: 0, suffix: "" },
      ],
      impact: 95,
      color: "#00D4FF",
      icon: "mesh",
    },
    {
      id: "video-brief",
      name: "Multimodal Video-to-Brief",
      shortName: "Video-to-Brief",
      description:
        "A client had thousands of brand videos and needed structured briefs for each one. I built a pipeline that watches videos with Amazon Nova Pro, extracts key information, and generates briefs - then fine-tuned Llama 3.1 8B with QLoRA across 8x A100s to bring the per-video cost down to half a cent.",
      tech: [
        "Amazon Nova Pro",
        "QLoRA",
        "Llama 3.1 8B",
        "SageMaker",
        "Python",
      ],
      metrics: [
        { label: "Briefs Generated", value: "3,867", suffix: "" },
        { label: "Cost per Brief", value: "$0.0051", suffix: "" },
        { label: "Fine-tune GPUs", value: 8, suffix: "x A100" },
      ],
      impact: 90,
      color: "#8B5CF6",
      icon: "video",
    },
    {
      id: "transaction-ai",
      name: "AI Transaction Categorization",
      shortName: "Transaction AI",
      description:
        "The original system was calling an LLM for every single transaction - expensive and slow. I added long-term memory so the agent remembers past categorizations and takes a fast path when it's seen something similar. Went from 8.3s to 1.2s per transaction and slashed costs by 93%.",
      tech: [
        "Bedrock AgentCore",
        "AgentCore LTM",
        "Haiku 4.5",
        "DynamoDB",
        "Lambda",
      ],
      metrics: [
        { label: "Latency", value: "8.3s", suffix: " to 1.2s" },
        { label: "Cost Reduction", value: 93, suffix: "%" },
      ],
      impact: 88,
      color: "#10B981",
      icon: "transaction",
    },
    {
      id: "text2sql",
      name: "Text2SQL Analytics Agent",
      shortName: "Text2SQL Agent",
      description:
        "Business teams shouldn't need to learn SQL to get answers from their data. I built an agent that takes plain English questions, writes Redshift SQL, and returns results - with guardrails to prevent SQL injection and PII leaks. Works across a 50+ column schema.",
      tech: [
        "Claude Sonnet",
        "Bedrock AgentCore",
        "Amazon Redshift",
        "API Gateway",
        "CDK",
      ],
      metrics: [
        { label: "Latency Reduction", value: 70, suffix: "%" },
        { label: "Schema Columns", value: 50, suffix: "+" },
        { label: "Queries / Week", value: 300, suffix: "+" },
      ],
      impact: 85,
      color: "#F59E0B",
      icon: "sql",
    },
    {
      id: "data-discovery",
      name: "Data Discovery Platform",
      shortName: "Data Discovery",
      description:
        "Companies lose track of their own data. I built a platform where teams can search, browse, and understand data assets across the organization - think Google for your internal data. React frontend, Python backend, all running on AWS.",
      tech: [
        "React",
        "Python",
        "AWS Amplify",
        "S3",
        "Glue",
        "Athena",
        "Lake Formation",
      ],
      metrics: [],
      impact: 75,
      color: "#EC4899",
      icon: "data",
    },
    {
      id: "voice-ai",
      name: "Voice AI Agent",
      shortName: "Voice AI",
      description:
        "A logistics startup was locked into an expensive voice AI vendor. I replaced it with a modular pipeline - speech-to-text, LLM reasoning, text-to-speech - all composable and swappable. Real-time conversations with sub-second response times over LiveKit.",
      tech: [
        "LiveKit",
        "React",
        "AWS Amplify",
        "Python",
        "WebRTC",
        "LLM Pipeline",
      ],
      metrics: [],
      impact: 70,
      color: "#6366F1",
      icon: "voice",
    },
    {
      id: "agentops-lab",
      kind: "OSS",
      name: "AgentOps Lab",
      shortName: "AgentOps",
      repo: "https://github.com/devjothish/agentops-lab",
      description:
        "You cannot tell whether an agent change helped unless you can see the run it produced. This is a LangGraph multi-agent analyst wired to a framework-agnostic reliability toolkit: every run emits an OpenTelemetry trajectory tree to Postgres, an eval engine scores the finished run, and a Next.js dashboard renders the waterfall so a retry or a critic loop-back is visible rather than inferred.",
      tech: [
        "LangGraph",
        "OpenTelemetry",
        "Postgres",
        "DuckDB",
        "Claude",
        "Next.js",
        "Python",
      ],
      metrics: [
        { label: "Tests Green", value: 57, suffix: "" },
        { label: "Agent Nodes", value: 5, suffix: "" },
      ],
      impact: 80,
      color: "#22D3EE",
      icon: "mesh",
    },
    {
      id: "rag-refusal-eval",
      kind: "OSS",
      name: "RAG Refusal Eval",
      shortName: "Refusal Eval",
      repo: "https://github.com/devjothish/rag-refusal-eval",
      description:
        "The dangerous RAG failure is not empty retrieval, it is retrieval that returns something topically adjacent and lets the model paraphrase a confident answer that was never in the corpus. This service answers over the Pydantic AI docs and validates every claim against a quote copied character for character out of a retrieved passage; a claim that cannot produce one never leaves the process.",
      tech: [
        "Pydantic AI",
        "Qdrant",
        "OpenTelemetry",
        "FastAPI",
        "Python",
      ],
      metrics: [
        { label: "Indexed Passages", value: "1,591", suffix: "" },
        { label: "Guardrail", value: "verbatim quote", suffix: "" },
      ],
      impact: 78,
      color: "#F472B6",
      icon: "sql",
    },
    {
      id: "agentic-rag",
      kind: "OSS",
      name: "Agentic RAG with Qdrant and Tavily",
      shortName: "Agentic RAG",
      repo: "https://github.com/devjothish/AgenticRAG",
      description:
        "A retrieval agent that decides where to look before it looks: indexed embeddings in Qdrant when the answer is in the corpus, a live Tavily web search when it is not. Multi-step agentic retrieval that beats single-shot RAG on questions needing both stored knowledge and current context.",
      tech: [
        "LangChain",
        "Qdrant",
        "Tavily",
        "Hugging Face",
        "Python",
      ],
      metrics: [],
      impact: 70,
      color: "#A3E635",
      icon: "data",
    },
  ],

  skills: {
    "AI / ML": [
      { name: "Strands Agents SDK", level: 95 },
      { name: "AWS Bedrock AgentCore", level: 95 },
      { name: "LangGraph", level: 90 },
      { name: "LangChain", level: 90 },
      { name: "QLoRA Fine-tuning", level: 85 },
      { name: "RAG Pipelines", level: 92 },
      { name: "RAGAS Evaluation", level: 85 },
      { name: "Prompt Engineering", level: 95 },
      { name: "Claude / GPT / Llama", level: 93 },
      { name: "Amazon Nova Pro", level: 88 },
      { name: "SageMaker", level: 85 },
      { name: "Hugging Face", level: 82 },
    ],
    Cloud: [
      { name: "AWS CDK", level: 92 },
      { name: "ECS Fargate", level: 88 },
      { name: "Lambda", level: 90 },
      { name: "API Gateway", level: 88 },
      { name: "DynamoDB", level: 87 },
      { name: "S3 / Glue / Athena", level: 85 },
      { name: "GCP Cloud Run", level: 80 },
      { name: "BigQuery", level: 78 },
      { name: "CloudFormation", level: 82 },
      { name: "Terraform", level: 75 },
    ],
    Backend: [
      { name: "Python", level: 95 },
      { name: "FastAPI", level: 88 },
      { name: "Node.js", level: 80 },
      { name: "PostgreSQL", level: 82 },
      { name: "Redis", level: 78 },
      { name: "Docker", level: 85 },
      { name: "REST APIs", level: 92 },
      { name: "GraphQL", level: 75 },
    ],
    Frontend: [
      { name: "React", level: 82 },
      { name: "TypeScript", level: 78 },
      { name: "HTML/CSS", level: 85 },
      { name: "Three.js", level: 70 },
      { name: "AWS Amplify", level: 80 },
    ],
  },

  certifications: {
    credlyProfile: "https://www.credly.com/users/jothiswaranarumugam",
    summary: {
      awsCount: 13,
      gcpCount: 3,
      gcpArchived: 4,
      totalCount: 16,
      goldenJacketYear: 2026,
      lastExpiration: "May 2029",
    },
    goldenJacket: {
      title: "The Golden Jacket",
      caption: "AWS sends a physical jacket to engineers holding all twelve plus active certifications. Roughly 1,500 holders worldwide.",
      year: 2026,
      verifyUrl: "https://www.credly.com/users/jothiswaranarumugam",
    },
    AWS: [
      {
        name: "Generative AI Developer",
        tier: "professional",
        suffix: "Professional",
        image: "https://images.credly.com/images/52c6e5ac-9516-4944-a4df-e31b23c9bbf2/blob",
      },
      {
        name: "Solutions Architect",
        tier: "professional",
        suffix: "Professional",
        image: "https://images.credly.com/images/2d84e428-9078-49b6-a804-13c15383d0de/image.png",
      },
      {
        name: "DevOps Engineer",
        tier: "professional",
        suffix: "Professional",
        image: "https://images.credly.com/images/bd31ef42-d460-493e-8503-39592aaf0458/image.png",
      },
      {
        name: "Advanced Networking",
        tier: "specialty",
        suffix: "Specialty",
        image: "https://images.credly.com/images/4d08274f-64c1-495e-986b-3143f51b1371/image.png",
      },
      {
        name: "Machine Learning",
        tier: "specialty",
        suffix: "Specialty",
        image: "https://images.credly.com/images/778bde6c-ad1c-4312-ac33-2fa40d50a147/image.png",
      },
      {
        name: "Security",
        tier: "specialty",
        suffix: "Specialty",
        image: "https://images.credly.com/images/53acdae5-d69f-4dda-b650-d02ed7a50dd7/image.png",
      },
      {
        name: "Solutions Architect",
        tier: "associate",
        suffix: "Associate",
        image: "https://images.credly.com/images/0e284c3f-5164-4b21-8660-0d84737941bc/image.png",
      },
      {
        name: "Developer",
        tier: "associate",
        suffix: "Associate",
        image: "https://images.credly.com/images/b9feab85-1a43-4f6c-99a5-631b88d5461b/image.png",
      },
      {
        name: "Machine Learning Engineer",
        tier: "associate",
        suffix: "Associate",
        image: "https://images.credly.com/images/1a634b4e-3d6b-4a74-b118-c0dcb429e8d2/image.png",
      },
      {
        name: "Data Engineer",
        tier: "associate",
        suffix: "Associate",
        image: "https://images.credly.com/images/e5c85d7f-4e50-431e-b5af-fa9d9b0596e7/image.png",
      },
      {
        name: "CloudOps Engineer",
        tier: "associate",
        suffix: "Associate",
        image: "https://images.credly.com/images/88a6405e-0f26-442a-95ed-f9b9db4c857e/blob",
      },
      {
        name: "AI Practitioner",
        tier: "foundational",
        suffix: "Foundational",
        image: "https://images.credly.com/images/4d4693bb-530e-4bca-9327-de07f3aa2348/image.png",
      },
      {
        name: "Cloud Practitioner",
        tier: "foundational",
        suffix: "Foundational",
        image: "https://images.credly.com/images/00634f82-b07f-4bbd-a6bb-53de397fc3a6/image.png",
      },
    ],
    GCP: [
      { name: "Machine Learning Engineer", tier: "professional", suffix: "Professional", active: true },
      { name: "DevOps Engineer", tier: "professional", suffix: "Professional", active: true },
      { name: "Database Engineer", tier: "professional", suffix: "Professional", active: true },
      { name: "Cloud Architect", tier: "professional", suffix: "Professional", active: false },
      { name: "Data Engineer", tier: "professional", suffix: "Professional", active: false },
      { name: "Cloud Developer", tier: "professional", suffix: "Professional", active: false },
      { name: "Cloud Engineer", tier: "associate", suffix: "Associate", active: false },
    ],
  },

  experience: [
    {
      role: "Lead Data and AI Engineer",
      company: "RevStar Consulting (AWS Advanced Tier Partner)",
      period: "Jun 2025 - Present",
      location: "Tampa, FL (Remote)",
      highlights: [
        "Ran point on 25+ client engagements - scoping architectures, estimating AWS costs, and building the AI systems myself. RAG pipelines, agentic workflows, fine-tuning - whatever the client needed.",
        "Built an 8-step healthcare claims pipeline where agents handle everything from intake to adjudication. Strands Agents SDK, Bedrock AgentCore, deployed on ECS Fargate.",
        "Cut per-video processing cost to $0.0051 by building a multimodal brief pipeline with Nova Pro. Processed 3,867 brand videos and fine-tuned Llama 3.1 8B with QLoRA on 8x A100s.",
        "Latency was 8.3 seconds per transaction - way too slow. Added dual-namespace long-term memory so the agent remembers past work. Got it down to 1.2s and cut costs by 93%.",
        "Non-technical teams needed data answers without writing SQL. Built an agent with Claude Sonnet that handles 50+ column schemas, with injection prevention and PII guardrails baked in.",
      ],
    },
    {
      role: "AI Engineer (Co-op)",
      company: "IM Digital",
      period: "May 2024 - May 2025",
      location: "Boca Raton, FL (Remote)",
      highlights: [
        "Built RAG pipelines on Qdrant with hybrid vector search - sub-300ms retrieval serving 1K+ queries a day for legal and product teams.",
        "Fine-tuned LLaMA and Mistral with LoRA/QLoRA on Vertex AI. Generation got 37% more accurate and token costs dropped 35%.",
        "Shipped multi-agent LLM APIs on Cloud Run with FastAPI. Added RBAC, rate limiting, and Prometheus/Grafana so we could actually monitor what the agents were doing.",
        "Hallucinations were a real problem. Set up CI/CD-driven eval with LangSmith and RAGAS - grounding scores improved 62%.",
      ],
    },
    {
      role: "GCP Cloud Engineer",
      company: "Cognizant (CTS)",
      period: "Jul 2021 - Aug 2023",
      location: "Hyderabad, India",
      highlights: [
        "Teams were spending days spinning up ML infrastructure. Automated it with Terraform, GKE, and BigQuery - setup time dropped 80% across 15+ projects.",
        "ML models kept missing SLAs. Rebuilt the serving layer with Vertex AI pipelines and optimized Dataflow ETL. SLA adherence improved 60%.",
        "Mentored 30+ engineers on GCP and ML infra best practices. Helped the org move from on-prem mindset to cloud-native.",
      ],
    },
  ],

  education: {
    degree: "Master of Science in Computer Science",
    school: "Florida State University",
    gpa: "3.72/4.0",
    period: "Aug 2023 - May 2025",
    location: "Tallahassee, FL",
  },
};

// Export for use in other modules
if (typeof module !== "undefined" && module.exports) {
  module.exports = PORTFOLIO_DATA;
}
